---
title: "VDH Ground Truth"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

## Read and clean data

```{r}
data <- read.csv("../vdh_open_data/VDH-COVID-19-PublicUseDataset-Vaccines-DosesAdministered_By-Race-Ethnicity.csv") %>% 
  mutate(date = as.Date(Report.Date, "%m/%d/%Y")) %>% 
  filter(Locality == "Richmond City") %>% 
  select(date, status = Vaccination.Status, race.eth = Race.and.Ethnicity, count = People.by.vaccination.status.count)
data.table::setDT(data)

sgData <- read.csv("sg-demographics.csv") %>% 
  mutate(date = as.Date(date))
sgData
```

## Analysis

```{r}
plt <- data %>%
  group_by(date) %>%
  mutate(total = sum(count)) %>% 
  group_by(date, race.eth) %>% 
  summarize(proportion = sum(count), total = mean(total)) %>% 
  filter(!race.eth %in% c("Other Race", "Two or more races", "Native American")) %>% 
  mutate(proportion = proportion / total) %>% 
  ggplot(aes(date, proportion, color = race.eth)) +
  geom_line(size = 1) +
  scale_y_continuous(labels = scales::percent) + 
  labs(subtitle = 'Percentage of those vaccinated by race or ethnicity in Richmond City', color = '') +
  theme(axis.text = element_text(size = 11), legend.text = element_text(size = 11), axis.title = element_blank(), plot.subtitle = element_text(size = 12.5))

ggsave(
  "richmond.png",
  plt,
  width = 7,
  height = 5.5,
  units = "in"
)

data %>%
  group_by(date, race.eth) %>%
  summarize(count = sum(count)) %>% 
  filter(!race.eth %in% c("Other Race", "Two or more races", "Native American")) %>% 
  ggplot(aes(date, count, color = race.eth)) +
  geom_line()

sgData %>% 
  group_by(date) %>%
  mutate(total = sum(count)) %>% 
  group_by(date, race.eth) %>% 
  summarize(proportion = sum(count), total = mean(total)) %>% 
  mutate(proportion = proportion / total) %>% 
  ggplot(aes(date, proportion, color = race.eth)) +
  geom_line()
```


